; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = debug

[env]
monitor_speed = 115200

[esp32_base]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
    -Iinclude
    -DHW_REV_1=1
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
    adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
    sparkfun/SparkFun Qwiic Scale NAU7802 Arduino Library@^1.0.4
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8

[env:debug]
extends = esp32_base
build_type = debug
build_flags =
    ${esp32_base.build_flags}
    -DDEBUG
    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG

[env:release]
extends = esp32_base
build_type = release
build_flags =
    ${esp32_base.build_flags}
    -DRELEASE
    -DLOG_LOCAL_LEVEL=ESP_LOG_NONE

[env:native]
platform = native
build_flags =
    -std=gnu++17
    -DNATIVE_TEST
    -DDEBUG
    -Iinclude
lib_deps =
